---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/spacetime version
      register: spacetime_test_output
    - name: spacetime version
      debug:
        msg: '{{ spacetime_test_output.stdout }}'
