---
- name: Testing andrewrothstein.spacetime
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'spacetime version'
      ansible.builtin.command: spacetime version
      changed_when: false
      register: spacetime_test_output
    - name: Output from 'spacetime version'
      ansible.builtin.debug:
        msg: '{{ spacetime_test_output.stdout }}'
