---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for installation at {{ spacetime_cli_exe }}
  ansible.builtin.stat:
    path: '{{ spacetime_cli_exe }}'
  register: spacetime_binary
- name: Downloading and installing SpacetimeDB
  when: not spacetime_binary.stat.exists
  block:
    - name: Downloading {{ spacetime_url }} to {{ spacetime_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ spacetime_url }}'
        dest: '{{ spacetime_tmp_archive }}'
        checksum: '{{ spacetime_checksum }}'
        mode: '644'
    - name: Mkdir {{ spacetime_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ spacetime_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ spacetime_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ spacetime_tmp_archive }}'
        dest: '{{ spacetime_install_dir }}'
        creates: '{{ spacetime_cli_exe }}'
  always:
    - name: Rm -f {{ spacetime_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ spacetime_tmp_archive }}'
        state: absent
- name: Linking from {{ spacetime_install_dir }} to {{ spacetime_links_dir }}...
  with_items:
    - spacetimedb-cli
    - spacetimedb-standalone
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ spacetime_install_dir }}/{{ item }}'
    dest: '{{ spacetime_links_dir }}/{{ item }}'
    state: link
